### ISSUE TITLE
REST API Board Response acl Field Type Changes Based on State

### ISSUE THREAD

**Issue by Llewxamris** [nextcloud/deck#1107]
**Describe the bug**
According the REST API docs, the `acl` field inside the Board entity is an array. When the board contains no ACL rules, it is an empty array. However, if the board contains ACL rules, the `acl` field is instead an object with `n` fields where `n` is the amount of ACL rules. Each field inside the `acl` has a key defined as the ID of the ACL rule, and a value of the ACL object shown inside the documentation.

**To Reproduce**
1. Call `/boards/{boardId}` on a board with no ACL rules
    - Field `acl` is an empty array
2. Add an ACL rule to the same board
3. Call `/boards/{boardId}` on the same board with the new ACL rule
    - Field `acl` is an object containing one field with the key set the the new ACL rule ID and the value set to the new ACL rule object

**Expected behavior**
Based on the documentation, I would assume `acl` would always be an array and new ACL rules would be added.

If this is not the expected behavior, the documentation should be updated to reflect this. As well, I would assume `acl` when empty would be an empty object.

**Client details:**
Curl 7.64.0

<details>
<summary>Server details</summary>

**Operating system**:
Ubuntu 18.04.2

**Nextcloud version:**
Nextcloud 15.0.8

**Where did you install Nextcloud from:**
 Installed via the Nextcloud Snap package

**Signing status:**

```
No errors have been found.
```
</details>

**Comment by juliushaertl** [comment]
Fixed with 0.6.3

**Comment by Llewxamris** [comment]
I'm still getting this behavior with version 0.6.4.
`curl -X GET "https://instance.com/index.php/apps/deck/api/v1.0/boards/7" -H "Content-Type: application/json" -H "OCS-APIRequest: true"`

Returns:
```
{
  ...
  "acl": {
     "12": {
         //  ACL rule object
        }
     }, 
   ...
}
```

Expected:
```
{
  ...
  "acl": [
        {
         //  ACL rule object
        }
     ],
   ...
}
```

**Comment by juliushaertl** [comment]
@Llewxamris 

Works just fine for me on 0.6.4:

```
"acl": [
    {
      "participant": {
        "primaryKey": "user2",
        "uid": "user2",
        "displayname": "user2"
      },
      "type": 0,
      "boardId": 1,
      "permissionEdit": false,
      "permissionShare": false,
      "permissionManage": false,
      "owner": false,
      "id": 1
    },
    {
      "participant": {
        "primaryKey": "user3",
        "uid": "user3",
        "displayname": "user3"
      },
      "type": 0,
      "boardId": 1,
      "permissionEdit": false,
      "permissionShare": false,
      "permissionManage": false,
      "owner": false,
      "id": 2
    }
  ],
```

**Comment by Llewxamris** [comment]
@juliushaertl 

Here is the full payload I am getting back. According to the Nextcloud admin panel, I am using Deck version 0.6.4 on Nextcloud 15.0.8. I have tried disabling, removing, and reinstalling Deck. That did not seem to make any difference.

Request:
`curl -X GET "https://myclouddomain.com/index.php/apps/deck/api/v1.0/boards/8" -H "Content-Type: application/json" -H "OCS-APIRequest: true"`

Response:
```
{
  "title": "Test",
  "owner": {
    "primaryKey": "max",
    "uid": "max",
    "displayname": "Maxwell"
  },
  "color": "ff0000",
  "archived": false,
  "labels": [
    {
      "title": "Finished",
      "color": "31CC7C",
      "boardId": 8,
      "cardId": null,
      "lastModified": 1562287715,
      "id": 29
    },
    {
      "title": "To review",
      "color": "317CCC",
      "boardId": 8,
      "cardId": null,
      "lastModified": 1562287715,
      "id": 30
    },
    {
      "title": "Action needed",
      "color": "FF7A66",
      "boardId": 8,
      "cardId": null,
      "lastModified": 1562287715,
      "id": 31
    },
    {
      "title": "Later",
      "color": "F1DB50",
      "boardId": 8,
      "cardId": null,
      "lastModified": 1562287715,
      "id": 32
    }
  ],
  "acl": {
    "14": {
      "participant": {
        "primaryKey": "test",
        "uid": "test",
        "displayname": "test"
      },
      "type": 0,
      "boardId": 8,
      "permissionEdit": true,
      "permissionShare": false,
      "permissionManage": false,
      "owner": false,
      "id": 14
    }
  },
  "permissions": {
    "PERMISSION_READ": true,
    "PERMISSION_EDIT": true,
    "PERMISSION_MANAGE": true,
    "PERMISSION_SHARE": true
  },
  "users": [
    {
      "primaryKey": "max",
      "uid": "max",
      "displayname": "Maxwell"
    },
    {
      "primaryKey": "test",
      "uid": "test",
      "displayname": "test"
    }
  ],
  "stacks": [],
  "deletedAt": 0,
  "lastModified": 1562605991,
  "id": 8
}
```

**Comment by Llewxamris** [comment]
After a weekly maintenance job I'm getting the expected response back. I don't know if it was response caching on my end, but everything is fine now. Thank you!

**Comment by juliushaertl** [comment]
In that case the opcache most likely still had the old version cached.
