### ISSUE TITLE
Sort labels by name

### ISSUE THREAD

**Issue by miguelsan** [nextcloud/deck#1700]
Labels/tags are shown in the order they were created, which has no relation whatsoever with their meaning. Meanwhile, the size of them may well grow with time. Once there are enough of them, they usually get some kind of organization through their appearance: same color for related labels. As their order cannot be changed, it becomes uncomfortably difficult to see their organization due to the randomly different colors.

I would like a way to sort the labels, at best through drag and drop.

An alphabetic ordering is probably very easy to implement as a first step and would help a little, although it has the danger of people starting to write things like "1-Customer name" that is why it should be the end of the story.

**Comment by juliushaertl** [comment]
I agree that we should start off with sorting by name to not over complicate this for now.

**Comment by jakobroehrl** [comment]
@juliushaertl 
Should I sort it here? https://github.com/nextcloud/deck/blob/master/src/components/board/TagsTabSidebar.vue#L4

**Comment by jakobroehrl** [comment]
solved with the next version

**Comment by jpaillet** [comment]
Hi everyone ! 
I still have the same issue when I filter labels in a board : they are still shown in the order they were created. 
Is it a question of version (I have Nextcloud 18.0.4 and Deck 1.0.5) ? 
Thanks!
Jeremy

**Comment by jakobroehrl** [comment]
Can't reproduce it with NC19, Deck 1.0.5.
If I create a new label named 'zzz' its show on the last place

**Comment by juliushaertl** [comment]
@jakobroehrl Maybe you can check again, they are indeed not sorted by name for me as well:

![image](https://user-images.githubusercontent.com/3404133/92373334-785de400-f0fe-11ea-9899-4b9f13b47fca.png)
