### ISSUE TITLE
Calendar Link opens in Tasks App instead of Deck.

### ISSUE THREAD

**Issue by vzsze** [nextcloud/deck#2711]
**Describe the bug**
When creating a Deck card with an end date, this end date is shown in the calendar. When clicking that entry in calendar, the deck entry is opened in the Tasks app instead of the Deck app.

**To Reproduce**
1. Create a Deck card with an end date. 
2. Go to Calendar tab.
3. Click on the deck card calendar entry.
4. Entry opens in Tasks tab instead of Deck tab.

**Expected behavior**
The Deck card entry should open in the Deck tab.

**Screenshots**

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version: 84.0.1
 - Device: Desktop

<details>
<summary>Server details</summary>

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Where did you install Nextcloud from:**

**Signing status:** No errors have been found.

**List of activated apps:**
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - checksum: 1.0.1
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - cookbook: 0.7.7
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - duplicatefinder: 0.0.4
 - epubreader: 1.4.5
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_fulltextsearch: 20.0.0
 - files_linkeditor: 1.1.3
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - fulltextsearch: 20.0.0
 - fulltextsearch_elasticsearch: 20.0.0
 - groupfolders: 8.2.0
 - impersonate: 1.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - viewer: 1.4.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - survey_client
 - user_ldap
 - user_status
 - weather_status
</details>

**Comment by juliushaertl** [comment]
Already fixed by https://github.com/nextcloud/deck/pull/2683 and will be part of the next maintenance release.

**Comment by MiningPickaxe** [comment]
Hello,

we are using Deck 1.6.0 and are still experiencing the described issue. When clicking on Calendar Entries made by Deck, they get opened in Tasks.

**Comment by pedroponte** [comment]
@juliushaertl I still have the same behaviour also, is this related with the response from https://github.com/nextcloud/deck/issues/4878#issuecomment-1695422983?
