### ISSUE TITLE
deleted_at on oc_deck_attachment after a new install

### ISSUE THREAD

**Issue by zero-24** [nextcloud/deck#2754]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**
I have recently installed deck on my nextcloud 20. After creating some decks and navigation arround the deck is empty again. After checking the logs it seems that the `oc_deck_attachment` table is missing the `deleted_at`. `occ db:add-missing-columns` didnt helped. So i manually added the column and now it works again.

**To Reproduce**
1. Go to deck
2. Click on create new deck content
3. naviagte arround
4. after some time (cache?) the deck does not show anything

**Expected behavior**
Deck shows the stuff i added to it. PS after adding the colums manually that stuff came back.

**Operating system**: linux

**Web server:** apache

**Database:** mysql

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.6

**Where did you install Nextcloud from:** NextCloud.com

**Are you using an external user-backend, if yes which one:** none (nextcloud default)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"YA-GPM-YyB09Ifqqr@7cEgAADgA","level":3,"time":"2021-01-26T07:35:24+00:00","remoteAddr":"XX","user":"XXX","app":"deck","method":"GET","url":"/index.php/apps/deck/stacks/4","message":{"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)' with params [3, 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":0,"Trace":[{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)' with params [3, 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'",{"errorInfo":["42S22",1054,"Unknown column 'deleted_at' in 'where clause'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":149,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["42S22",1054,"Unknown column 'deleted_at' in 'where clause'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)' with params [3, 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'"]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":914,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["42S22",1054,"Unknown column 'deleted_at' in 'where clause'"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)",{"1":3,"2":0}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)",[3,0],[1,1],null]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = :dcValue1) AND (`deleted_at` = :dcValue2)",{"dcValue1":3,"dcValue2":0},{"dcValue1":1,"dcValue2":1}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Db/AttachmentMapper.php","line":113,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/AttachmentService.php","line":150,"function":"findAll","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/CardService.php","line":103,"function":"count","class":"OCA\\Deck\\Service\\AttachmentService","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":92,"function":"enrich","class":"OCA\\Deck\\Service\\CardService","type":"->","args":[{"id":3,"__class__":"OCA\\Deck\\Db\\Card"}]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":100,"function":"enrichStackWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":143,"function":"enrichStacksWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":5,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":11,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":12,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":13,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":14,"__class__":"OCA\\Deck\\Db\\Stack"}],-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Controller/StackController.php","line":47,"function":"findAll","class":"OCA\\Deck\\Service\\StackService","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Deck\\Controller\\StackController","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\StackController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"boardId":"4","_route":"deck.stack.index"}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/stacks/4"]},{"file":"/www/htdocs/w00f930c/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":60,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":"42S22","Trace":[{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":906,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)",[3,0],[1,1],null]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = :dcValue1) AND (`deleted_at` = :dcValue2)",{"dcValue1":3,"dcValue2":0},{"dcValue1":1,"dcValue2":1}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Db/AttachmentMapper.php","line":113,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/AttachmentService.php","line":150,"function":"findAll","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/CardService.php","line":103,"function":"count","class":"OCA\\Deck\\Service\\AttachmentService","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":92,"function":"enrich","class":"OCA\\Deck\\Service\\CardService","type":"->","args":[{"id":3,"__class__":"OCA\\Deck\\Db\\Card"}]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":100,"function":"enrichStackWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":143,"function":"enrichStacksWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":5,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":11,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":12,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":13,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":14,"__class__":"OCA\\Deck\\Db\\Stack"}],-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Controller/StackController.php","line":47,"function":"findAll","class":"OCA\\Deck\\Service\\StackService","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Deck\\Controller\\StackController","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\StackController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"boardId":"4","_route":"deck.stack.index"}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/stacks/4"]},{"file":"/www/htdocs/w00f930c/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":129,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":"42S22","Trace":[{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":127,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":906,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = ?) AND (`deleted_at` = ?)",[3,0],[1,1],null]},{"file":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_deck_attachment` WHERE (`card_id` = :dcValue1) AND (`deleted_at` = :dcValue2)",{"dcValue1":3,"dcValue2":0},{"dcValue1":1,"dcValue2":1}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Db/AttachmentMapper.php","line":113,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/AttachmentService.php","line":150,"function":"findAll","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/CardService.php","line":103,"function":"count","class":"OCA\\Deck\\Service\\AttachmentService","type":"->","args":[3]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":92,"function":"enrich","class":"OCA\\Deck\\Service\\CardService","type":"->","args":[{"id":3,"__class__":"OCA\\Deck\\Db\\Card"}]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":100,"function":"enrichStackWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Service/StackService.php","line":143,"function":"enrichStacksWithCards","class":"OCA\\Deck\\Service\\StackService","type":"->","args":[[{"id":4,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":5,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":11,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":12,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":13,"__class__":"OCA\\Deck\\Db\\Stack"},{"id":14,"__class__":"OCA\\Deck\\Db\\Stack"}],-1]},{"file":"/www/htdocs/w00f930c/nextcloud/apps/deck/lib/Controller/StackController.php","line":47,"function":"findAll","class":"OCA\\Deck\\Service\\StackService","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Deck\\Controller\\StackController","type":"->","args":["4"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Deck\\Controller\\StackController"},"index"]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\StackController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"boardId":"4","_route":"deck.stack.index"}]},{"file":"/www/htdocs/w00f930c/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/deck/stacks/4"]},{"file":"/www/htdocs/w00f930c/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/htdocs/w00f930c/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":127}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Safari/537.36","version":"20.0.6.1"}
```

#### Browser log
```
none
```

</details>

**Comment by juliushaertl** [comment]
Did you have some old version of deck installed at some point and probably skipped quite a lot of releases and reinstalled the deck app again now?

Can you maybe share the output of `occ migrations:status deck` ?

**Comment by zero-24** [comment]
![image](https://user-images.githubusercontent.com/2596554/106199975-851acb80-61b6-11eb-87d0-172ae626cce8.png)

Thats the output does that help?

**Comment by zero-24** [comment]
> Did you have some old version of deck installed at some point and probably skipped quite a lot of releases and reinstalled the deck app again now?

It could be or better i can not indefently say that this was not the case but must be a few years. Would the error be expected in such case?

**Comment by zero-24** [comment]
I have now fixed it manually on the database but it might make sense to have some kind of "cleanup" command that could apply such changes?

**Comment by quenenni** [comment]
Same problem here on a NC 23.
I don't know when it started, when the app Deck was first installed.
I updated to v1.6.1 today, but the problem persists.

What I see is that the active table structure for nc_deck_attachment is:
```
nc_deck_attachment | CREATE TABLE `nc_deck_attachment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8mb4_bin NOT NULL,
  `card_id` bigint(20) NOT NULL,
  `type` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `data` longtext COLLATE utf8mb4_bin DEFAULT NULL,
  `last_modified` bigint(20) unsigned DEFAULT 0,
  `created_at` bigint(20) unsigned DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
```

The only reference to that table 'deck_attachment' (creation or update  or cleaning) found in the migration folder is in this file:
apps/deck/lib/Migration/Version1000Date20200306161713.php
```
        if (!$schema->hasTable('deck_attachment')) {
            $table = $schema->createTable('deck_attachment');
            $table->addColumn('id', 'integer', [
                'autoincrement' => true,
                'notnull' => true,
                'length' => 4,
            ]);
            $table->addColumn('card_id', 'bigint', [
                'notnull' => true,
                'length' => 8,
            ]);
            $table->addColumn('type', 'string', [
                'notnull' => true,
                'length' => 64,
            ]);
            $table->addColumn('data', 'string', [
                'notnull' => false,
            ]);
            $table->addColumn('last_modified', 'bigint', [
                'notnull' => false,
                'length' => 8,
                'default' => 0,
                'unsigned' => true,
            ]);
            $table->addColumn('created_at', 'bigint', [
                'notnull' => false,
                'length' => 8,
                'default' => 0,
                'unsigned' => true,
            ]);
            $table->addColumn('created_by', 'string', [
                'notnull' => true,
                'length' => 64,
            ]);
            $table->addColumn('deleted_at', 'bigint', [
                'notnull' => false,
                'length' => 8,
                'default' => 0,
                'unsigned' => true,
            ]);
            $table->setPrimaryKey(['id']);
        }
```
This structure is quite different from the one active in the DB.
- 1 column "title" that came from ? (first install I suppose)
- 2 columns missing (created_by & deleted_at)

I think the Deck app need a check / cleaning / update of the table structures on each update.

Here is the error in the log when the cron is executed:
```
{"reqId":"ZyClSRkTeB0u1QrNN0Ls","level":3,"time":"2022-04-04T22:25:35+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Deck\\Cron\\DeleteCron, arguments: )","userAgent":"--","version":"23.0.0.10","exception":{"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":1054,"Trace":[{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Connection.php","line":1780,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Connection.php","line":1719,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Connection.php","line":1067,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/Connection.php","line":236,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Db/AttachmentMapper.php","line":143,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Cron/DeleteCron.php","line":58,"function":"findToDelete","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Deck\\Cron\\DeleteCron","type":"->"},{"file":"/opt/nextcloud/instances/aaia/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"}],"File":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":65,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":1054,"Trace":[{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":94,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Connection.php","line":1057,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/Connection.php","line":236,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Db/AttachmentMapper.php","line":143,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Cron/DeleteCron.php","line":58,"function":"findToDelete","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Deck\\Cron\\DeleteCron","type":"->"},{"file":"/opt/nextcloud/instances/aaia/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"}],"File":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause'","Code":"42S22","Trace":[{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":92,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Connection.php","line":1057,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/Connection.php","line":236,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Db/AttachmentMapper.php","line":143,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/opt/nextcloud/instances/aaia/apps/deck/lib/Cron/DeleteCron.php","line":58,"function":"findToDelete","class":"OCA\\Deck\\Db\\AttachmentMapper","type":"->"},{"file":"/opt/nextcloud/instances/aaia/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Deck\\Cron\\DeleteCron","type":"->"},{"file":"/opt/nextcloud/instances/aaia/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"}],"File":"/opt/nextcloud/instances/aaia/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":92}},"CustomMessage":"Error while running background job (class: OCA\\Deck\\Cron\\DeleteCron, arguments: )"}}
```
