### ISSUE TITLE
Deck access problem

### ISSUE THREAD

**Issue by dirigit** [nextcloud/deck#52]
### Steps to reproduce

1. Create a deck
2.  click on automatic assigned user (you)
3. watch screen
4. choose another app (calendar, files, whatever)
5. choose Deck again and watch screen

### Expected behaviour
Related to 2: Something about your account should be visible
Related to 5: Created decks should be shown

### Actual behaviour

Related to 2: Message "Error while loading stacks"

Related to 5: Already created decks are not shown, onliest choice: create new deck. Created decks are in database (_deck_boards), no other entry in deck related tables except _deck_labels (preset).

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
mysql 5.5.54
**PHP version:**
7.0.15, memory limit 512 MB
**Server version:** (see your admin page)
nextcloud 11.0.1.2
**Deck version:** (see the apps page)
0.1.1

**Updated from an older installed version or fresh install:**
both
** apps installed **
files, activity, gallery,calendar, email, contacts, tasks, notes, bookmarks, deck
**The content of config/config.php:**

  'default_language' => 'de',
  'defaultapp' => 'calendar,documents,gallery,files',
  'knowledgebaseenabled' => true,
  'enable_avatars' => true,
  'theme' => '',
  'loglevel' => 4,
  'trashbin_retention_obligation' => 'auto',
  'app.mail.transport' => 'php-mail',
  'appcodechecker' => true,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'appstoreenabled' => true,
  'appstore.experimental.enabled' => true,
  'enable_previews' => true,
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'logtimezone' => 'Europe/Berlin',
  'updater.release.channel' => 'stable',

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no, because recovery is unreliable
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox, Edge
**Operating system:**
Win, Linux, BSD, Android

#### Log file (data/nextcloud.log)
No entry since several days

cu, diri

**Comment by juliushaertl** [comment]
Thanks for your bug report. I cannot reproduce the issue.
Are there any errors in the browser console?

**Comment by dirigit** [comment]
Sorry for late answer ...
Onliest messag I get:
Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.

**Comment by 9662** [comment]
Not sure if it's the same issue, but try the following (you need to be admin):
1. Create a group, e.g., `Deckers`
2. Create a user, e.g., `Kan Ban`
3. Assign `Kan Ban` to group `Deckers`
4. Create a deck, e.g., `Quack`
5. Share `Quack` with group `Deckers`
6. Log in as `Kan Ban`
7. Open the deck `Quack`

Instead of seeing the deck, Mr Ban gets the error mentioned by @dirigit .

btw, I know this application is still at an early stage, but good job nevertheless. I'm very impressed! 👍

**Comment by dirigit** [comment]
Looks like the same.

When getting the error I'm logged in as admin, create a deck and can't see it after changing the app.

**Comment by dirigit** [comment]
Problem still valid after nextcloud update to 11.0.2.

**Comment by juliushaertl** [comment]
@dirigit @9662 Are you using a custom database table prefix other than oc_ ? That might explain the issue and should be fixed by #62.

**Comment by dirigit** [comment]
@juliushaertl 
Yes, I'm using individual prefixes with every application being online.

Will give #62 a try today.

Thank you!

**Comment by dirigit** [comment]
Ok, tested it  and confirm it being fixed. Decks are shown now.

But, something in stacks is still wrong ... doesn't work (creation no error, no view). Must have another reasen.

**Comment by dirigit** [comment]
Changing color of deck doesn't work as well (change to some other app and back).

**Comment by LollenJumplan** [comment]
dirigit: Your issue might be related to mine. I created a new issue here: https://github.com/nextcloud/deck/issues/89

**Comment by juliushaertl** [comment]
@dirigit Can you retry with the current version 0.1.3 as we had quite some bugs fixed.

**Comment by dirigit** [comment]
All looks like being fixed with v1.4.
Thanks a lot!
